### ISSUE TITLE
淘宝好评：批量加图

### ISSUE THREAD

**Issue by Arrtime** [nekozero/neko0-web-tools#1]
你好 请问可以添加批量加图的功能吗 字数 图片好像都会影响淘宝分。。

**Comment by MitsukiJoe** [comment]
抱歉现在才看到

评论方面确实现在的规则好像改为了图片+10个子以上就可以，不像以前是逼着买家写作文80字了
但是也并不能用以前的“好评专用图”之类的蒙混过关了，对这方面也有检测，最好还是自己动手上传商品相关图片啦

PS.不过主要还是我没找到怎么用JS来进行文件赋值TvT
在浏览器中出于安全性考虑，JS是不能直接设置File的value值的

**Comment by Arrtime** [comment]
还是谢谢你的回复（科普）呀！希望你有朝一日想到解决方法吧。哈哈（*＾-＾*）
