### ISSUE TITLE
淘宝好评：引入ChatGPT来描述产品相关的评价

### ISSUE THREAD

**Issue by Cp0204** [nekozero/neko0-web-tools#6]
RT
prompt：
> "写一段关于" + title + "的商品评价，口语化"

**Comment by Cp0204** [comment]
https://github.com/nekozero/neko0-web-tools/pull/7

![GIF](https://user-images.githubusercontent.com/5239753/232384165-9d4135c4-68d7-408b-bf38-d9a690931181.gif)

**Comment by MitsukiJoe** [comment]
Thanks for your pull request, it has been merged
